# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct TimeseriesApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `TimeseriesApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ TimeseriesApi }) = "https://heatpumpmonitor.org"

const _returntypes_timeseries_available_TimeseriesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => TimeseriesAvailable,
)

function _oacinternal_timeseries_available(_api::TimeseriesApi, id::Int64; _mediaType=nothing)
    OpenAPI.validate_param("id", "timeseries_available", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_timeseries_available_TimeseriesApi, "/timeseries/available", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List available timeseries feeds for a system

Returns the set of timeseries feeds available for the system, with metadata for each feed.

Params:
- id::Int64 (required)

Return: TimeseriesAvailable, OpenAPI.Clients.ApiResponse
"""
function timeseries_available(_api::TimeseriesApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_timeseries_available(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function timeseries_available(_api::TimeseriesApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_timeseries_available(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_timeseries_data_TimeseriesApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, Vector{Vector{Any}}},
)

function _oacinternal_timeseries_data(_api::TimeseriesApi, id::Int64, feeds::String; start=nothing, __end__=nothing, interval=nothing, average=nothing, delta=nothing, timeformat=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "timeseries_data", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_timeseries_data_TimeseriesApi, "/timeseries/data", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "feeds", feeds; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_param(_ctx.query, "start", start; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "end", __end__; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "interval", interval; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "average", average; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "delta", delta; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "timeformat", timeformat; style="form", is_explode=true)  # type String
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Fetch timeseries data for one or more feeds

Returns timeseries data for a given system. Response is a JSON object keyed by feed name; each value is an array of `[timestamp_ms, value]` pairs (timestamp is unix epoch in milliseconds; value is a number, possibly null).  Requesting a feed name that does not exist on the system causes the upstream PHP backend to inline a warning into the response body (HTTP 200 but invalid JSON). Always call /timeseries/available first to discover valid feed names.

Params:
- id::Int64 (required)
- feeds::String (required)
- start::Int64
- __end__::Int64
- interval::Int64
- average::Int64
- delta::Int64
- timeformat::String

Return: Dict{String, Vector{Vector{Any}}}, OpenAPI.Clients.ApiResponse
"""
function timeseries_data(_api::TimeseriesApi, id::Int64, feeds::String; start=nothing, __end__=nothing, interval=nothing, average=nothing, delta=nothing, timeformat=nothing, _mediaType=nothing)
    _ctx = _oacinternal_timeseries_data(_api, id, feeds; start=start, __end__=__end__, interval=interval, average=average, delta=delta, timeformat=timeformat, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function timeseries_data(_api::TimeseriesApi, response_stream::Channel, id::Int64, feeds::String; start=nothing, __end__=nothing, interval=nothing, average=nothing, delta=nothing, timeformat=nothing, _mediaType=nothing)
    _ctx = _oacinternal_timeseries_data(_api, id, feeds; start=start, __end__=__end__, interval=interval, average=average, delta=delta, timeformat=timeformat, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export timeseries_available
export timeseries_data
