# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

struct SystemApi <: OpenAPI.APIClientImpl
    client::OpenAPI.Clients.Client
end

"""
The default API base path for APIs in `SystemApi`.
This can be used to construct the `OpenAPI.Clients.Client` instance.
"""
basepath(::Type{ SystemApi }) = "https://heatpumpmonitor.org"

const _returntypes_get_system_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => SystemMeta,
)

function _oacinternal_get_system(_api::SystemApi, id::Int64; _mediaType=nothing)
    OpenAPI.validate_param("id", "get_system", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_get_system_SystemApi, "/system/get.json", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Get metadata for a single system

Returns meta data for the selected system. The shape is a subset of /system/list/public.json — the following fields are present only in /list and absent here: `heatpump_elec_feedid`, `heatpump_heat_feedid`, `heatpump_elec_ago`, `heatpump_heat_ago`, `heatpump_max_age`, `heatpump_model_id`, `heatpump_url`, `manufacturer_id`, `photo_count`.

Params:
- id::Int64 (required)

Return: SystemMeta, OpenAPI.Clients.ApiResponse
"""
function get_system(_api::SystemApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_system(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function get_system(_api::SystemApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_get_system(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_public_systems_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{SystemMeta},
)

function _oacinternal_list_public_systems(_api::SystemApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_public_systems_SystemApi, "/system/list/public.json", [])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List public systems

List of public systems with all system form meta data.

Params:

Return: Vector{SystemMeta}, OpenAPI.Clients.ApiResponse
"""
function list_public_systems(_api::SystemApi; _mediaType=nothing)
    _ctx = _oacinternal_list_public_systems(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_public_systems(_api::SystemApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_list_public_systems(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_list_user_systems_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{SystemMeta},
    Regex("^" * replace("401", "x"=>".") * "\$") => Nothing,
)

function _oacinternal_list_user_systems(_api::SystemApi; _mediaType=nothing)
    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_list_user_systems_SystemApi, "/system/list/user.json", ["sessionCookie", ])
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""List the logged-in user's systems

When logged in this returns the system list for the logged-in user. Requires an authenticated session cookie established via the web UI at /user/login.

Params:

Return: Vector{SystemMeta}, OpenAPI.Clients.ApiResponse
"""
function list_user_systems(_api::SystemApi; _mediaType=nothing)
    _ctx = _oacinternal_list_user_systems(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function list_user_systems(_api::SystemApi, response_stream::Channel; _mediaType=nothing)
    _ctx = _oacinternal_list_user_systems(_api; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_all_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, SystemStats},
)

function _oacinternal_stats_all(_api::SystemApi; id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_all", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_all_SystemApi, "/system/stats/all", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Stats summary over all available time

Returns a map keyed by system ID (as string).

Params:
- id::Int64

Return: Dict{String, SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_all(_api::SystemApi; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_all(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_all(_api::SystemApi, response_stream::Channel; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_all(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_custom_window_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, SystemStats},
)

function _oacinternal_stats_custom_window(_api::SystemApi; id=nothing, start=nothing, __end__=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_custom_window", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_custom_window_SystemApi, "/system/stats", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_param(_ctx.query, "start", start; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_param(_ctx.query, "end", __end__; style="form", is_explode=true)  # type Date
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Stats summary for a custom time window

Returns a map keyed by system ID (as string).

Params:
- id::Int64
- start::Date
- __end__::Date

Return: Dict{String, SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_custom_window(_api::SystemApi; id=nothing, start=nothing, __end__=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_custom_window(_api; id=id, start=start, __end__=__end__, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_custom_window(_api::SystemApi, response_stream::Channel; id=nothing, start=nothing, __end__=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_custom_window(_api; id=id, start=start, __end__=__end__, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_daily_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => String,
)

function _oacinternal_stats_daily(_api::SystemApi, id::Int64; _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_daily", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_daily_SystemApi, "/system/stats/daily", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["text/plain", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Daily stats as CSV

Returns all daily data for the specified system as CSV. The first row is the header; columns include the SystemStats fields plus `cooling_*` and `weighted_*`. Date-range parameters are not yet supported by the upstream service.  Note: upstream returns the body with `Content-Type: text/plain; charset=UTF-8` (not `text/csv`).

Params:
- id::Int64 (required)

Return: String, OpenAPI.Clients.ApiResponse
"""
function stats_daily(_api::SystemApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stats_daily(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_daily(_api::SystemApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stats_daily(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_last30_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, SystemStats},
)

function _oacinternal_stats_last30(_api::SystemApi; id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_last30", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_last30_SystemApi, "/system/stats/last30", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Stats summary for the last 30 days

Returns a map keyed by system ID (as string).

Params:
- id::Int64

Return: Dict{String, SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_last30(_api::SystemApi; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last30(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_last30(_api::SystemApi, response_stream::Channel; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last30(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_last365_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, SystemStats},
)

function _oacinternal_stats_last365(_api::SystemApi; id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_last365", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_last365_SystemApi, "/system/stats/last365", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Stats summary for the last 365 days

Returns a map keyed by system ID (as string).

Params:
- id::Int64

Return: Dict{String, SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_last365(_api::SystemApi; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last365(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_last365(_api::SystemApi, response_stream::Channel; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last365(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_last7_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, SystemStats},
)

function _oacinternal_stats_last7(_api::SystemApi; id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_last7", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_last7_SystemApi, "/system/stats/last7", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Stats summary for the last 7 days

Returns a map keyed by system ID (as string). When `id` is provided the map contains a single entry.

Params:
- id::Int64

Return: Dict{String, SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_last7(_api::SystemApi; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last7(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_last7(_api::SystemApi, response_stream::Channel; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last7(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_last90_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Dict{String, SystemStats},
)

function _oacinternal_stats_last90(_api::SystemApi; id=nothing, _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_last90", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_last90_SystemApi, "/system/stats/last90", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Stats summary for the last 90 days

Returns a map keyed by system ID (as string).

Params:
- id::Int64

Return: Dict{String, SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_last90(_api::SystemApi; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last90(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_last90(_api::SystemApi, response_stream::Channel; id=nothing, _mediaType=nothing)
    _ctx = _oacinternal_stats_last90(_api; id=id, _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

const _returntypes_stats_monthly_SystemApi = Dict{Regex,Type}(
    Regex("^" * replace("200", "x"=>".") * "\$") => Vector{SystemStats},
)

function _oacinternal_stats_monthly(_api::SystemApi, id::Int64; _mediaType=nothing)
    OpenAPI.validate_param("id", "stats_monthly", :minimum, id, 1, false)

    _ctx = OpenAPI.Clients.Ctx(_api.client, "GET", _returntypes_stats_monthly_SystemApi, "/system/stats/monthly", [])
    OpenAPI.Clients.set_param(_ctx.query, "id", id; style="form", is_explode=true)  # type Int64
    OpenAPI.Clients.set_header_accept(_ctx, ["application/json", ])
    OpenAPI.Clients.set_header_content_type(_ctx, (_mediaType === nothing) ? [] : [_mediaType])
    return _ctx
end

@doc raw"""Monthly stats as JSON

Returns a JSON array of per-month stats records for the specified system. Each element is a SystemStats record covering one calendar month, with `timestamp` (start-of-month, unix epoch seconds) identifying the month. All numeric fields are returned as strings by this endpoint.

Params:
- id::Int64 (required)

Return: Vector{SystemStats}, OpenAPI.Clients.ApiResponse
"""
function stats_monthly(_api::SystemApi, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stats_monthly(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx)
end

function stats_monthly(_api::SystemApi, response_stream::Channel, id::Int64; _mediaType=nothing)
    _ctx = _oacinternal_stats_monthly(_api, id; _mediaType=_mediaType)
    return OpenAPI.Clients.exec(_ctx, response_stream)
end

export get_system
export list_public_systems
export list_user_systems
export stats_all
export stats_custom_window
export stats_daily
export stats_last30
export stats_last365
export stats_last7
export stats_last90
export stats_monthly
