# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module HeatpumpMonitorAPIAPI

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1.2.0"

include("modelincludes.jl")

include("apis/api_SystemApi.jl")
include("apis/api_TimeseriesApi.jl")

# export models
export BoundaryMetering
export SystemMeta
export SystemMetaBetateach
export SystemMetaHeatpumpElecFeedid
export SystemMetaHeatpumpHeatFeedid
export SystemStats
export SystemStatsCombinedDataLength
export SystemStatsCombinedElecKwh
export SystemStatsCombinedElecMean
export SystemStatsCombinedFlowTMean
export SystemStatsCombinedPrcCarnot
export SystemStatsCombinedStarts
export SystemStatsCoolingHeatKwh
export SystemStatsFromEnergyFeedsElecKwh
export SystemStatsId
export SystemStatsQualityElec
export SystemStatsStarts
export SystemStatsStartsPerHour
export SystemStatsTimestamp
export SystemStatsUnitRateAgile
export SystemStatsUnitRateCosy
export SystemStatsUnitRateGo
export SystemStatsWeightedTimeOn
export SystemStatsWeightedTimeTotal
export TimeseriesAvailable
export TimeseriesFeed

# export operations
export SystemApi
export TimeseriesApi

end # module HeatpumpMonitorAPIAPI
