# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeseriesFeed
Metadata for a single feed. &#x60;unit&#x60; is omitted for feeds whose unit is not configured upstream.

    TimeseriesFeed(;
        start_time=nothing,
        end_time=nothing,
        interval=nothing,
        npoints=nothing,
        unit=nothing,
    )

    - start_time::Int64 : Unix epoch seconds.
    - end_time::Int64 : Unix epoch seconds.
    - interval::Float64 : Mean sampling interval in seconds.
    - npoints::Int64 : Total number of samples.
    - unit::String : Engineering unit (e.g. W, kWh, C). May be absent.
"""
Base.@kwdef mutable struct TimeseriesFeed <: OpenAPI.APIModel
    start_time::Union{Nothing, Int64} = nothing
    end_time::Union{Nothing, Int64} = nothing
    interval::Union{Nothing, Float64} = nothing
    npoints::Union{Nothing, Int64} = nothing
    unit::Union{Nothing, String} = nothing

    function TimeseriesFeed(start_time, end_time, interval, npoints, unit, )
        o = new(start_time, end_time, interval, npoints, unit, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TimeseriesFeed

const _property_types_TimeseriesFeed = Dict{Symbol,String}(Symbol("start_time")=>"Int64", Symbol("end_time")=>"Int64", Symbol("interval")=>"Float64", Symbol("npoints")=>"Int64", Symbol("unit")=>"String", )
OpenAPI.property_type(::Type{ TimeseriesFeed }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeseriesFeed[name]))}

function OpenAPI.check_required(o::TimeseriesFeed)
    true
end

function OpenAPI.validate_properties(o::TimeseriesFeed)
    OpenAPI.validate_property(TimeseriesFeed, Symbol("start_time"), o.start_time)
    OpenAPI.validate_property(TimeseriesFeed, Symbol("end_time"), o.end_time)
    OpenAPI.validate_property(TimeseriesFeed, Symbol("interval"), o.interval)
    OpenAPI.validate_property(TimeseriesFeed, Symbol("npoints"), o.npoints)
    OpenAPI.validate_property(TimeseriesFeed, Symbol("unit"), o.unit)
end

function OpenAPI.validate_property(::Type{ TimeseriesFeed }, name::Symbol, val)





end
