# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_quality_elec
Coverage / data-quality indicator for the electrical signal in this window.

    SystemStatsQualityElec(; value=nothing)
"""
mutable struct SystemStatsQualityElec <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsQualityElec() = new()
    SystemStatsQualityElec(value) = new(value)
end # type SystemStatsQualityElec

function OpenAPI.property_type(::Type{ SystemStatsQualityElec }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsQualityElec, name)
end
