# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_unit_rate_cosy
Octopus Cosy mean unit rate over the window (£/kWh).

    SystemStatsUnitRateCosy(; value=nothing)
"""
mutable struct SystemStatsUnitRateCosy <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsUnitRateCosy() = new()
    SystemStatsUnitRateCosy(value) = new(value)
end # type SystemStatsUnitRateCosy

function OpenAPI.property_type(::Type{ SystemStatsUnitRateCosy }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsUnitRateCosy, name)
end
