# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_unit_rate_go
Octopus Go mean unit rate over the window (£/kWh).

    SystemStatsUnitRateGo(; value=nothing)
"""
mutable struct SystemStatsUnitRateGo <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsUnitRateGo() = new()
    SystemStatsUnitRateGo(value) = new(value)
end # type SystemStatsUnitRateGo

function OpenAPI.property_type(::Type{ SystemStatsUnitRateGo }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsUnitRateGo, name)
end
