# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_weighted_time_total
Total weighted seconds in the window.

    SystemStatsWeightedTimeTotal(; value=nothing)
"""
mutable struct SystemStatsWeightedTimeTotal <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemStatsWeightedTimeTotal() = new()
    SystemStatsWeightedTimeTotal(value) = new(value)
end # type SystemStatsWeightedTimeTotal

function OpenAPI.property_type(::Type{ SystemStatsWeightedTimeTotal }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsWeightedTimeTotal, name)
end
