# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemMeta_heatpump_elec_feedid
Feed ID for electrical input. Returned as &#x60;false&#x60; for unauthenticated requests. /list only.

    SystemMetaHeatpumpElecFeedid(; value=nothing)
"""
mutable struct SystemMetaHeatpumpElecFeedid <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Bool, Int64 }
    SystemMetaHeatpumpElecFeedid() = new()
    SystemMetaHeatpumpElecFeedid(value) = new(value)
end # type SystemMetaHeatpumpElecFeedid

function OpenAPI.property_type(::Type{ SystemMetaHeatpumpElecFeedid }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemMetaHeatpumpElecFeedid, name)
end
