# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_timestamp
Unix epoch seconds. For /system/stats/monthly this is the start-of-month timestamp; for some systems it is &#x60;false&#x60;.

    SystemStatsTimestamp(; value=nothing)
"""
mutable struct SystemStatsTimestamp <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Bool, Float64, String }
    SystemStatsTimestamp() = new()
    SystemStatsTimestamp(value) = new(value)
end # type SystemStatsTimestamp

function OpenAPI.property_type(::Type{ SystemStatsTimestamp }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsTimestamp, name)
end
