# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_starts
Present in /system/stats/monthly entries (alongside &#x60;combined_starts&#x60;).

    SystemStatsStarts(; value=nothing)
"""
mutable struct SystemStatsStarts <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemStatsStarts() = new()
    SystemStatsStarts(value) = new(value)
end # type SystemStatsStarts

function OpenAPI.property_type(::Type{ SystemStatsStarts }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsStarts, name)
end
