# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_cooling_heat_kwh
Heat removed in cooling mode (kWh).

    SystemStatsCoolingHeatKwh(; value=nothing)
"""
mutable struct SystemStatsCoolingHeatKwh <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsCoolingHeatKwh() = new()
    SystemStatsCoolingHeatKwh(value) = new(value)
end # type SystemStatsCoolingHeatKwh

function OpenAPI.property_type(::Type{ SystemStatsCoolingHeatKwh }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCoolingHeatKwh, name)
end
