# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_weighted_time_on
Seconds the heat pump was running, weighted.

    SystemStatsWeightedTimeOn(; value=nothing)
"""
mutable struct SystemStatsWeightedTimeOn <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemStatsWeightedTimeOn() = new()
    SystemStatsWeightedTimeOn(value) = new(value)
end # type SystemStatsWeightedTimeOn

function OpenAPI.property_type(::Type{ SystemStatsWeightedTimeOn }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsWeightedTimeOn, name)
end
