# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_from_energy_feeds_elec_kwh
Electrical energy from cumulative kWh feeds rather than power integration.

    SystemStatsFromEnergyFeedsElecKwh(; value=nothing)
"""
mutable struct SystemStatsFromEnergyFeedsElecKwh <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsFromEnergyFeedsElecKwh() = new()
    SystemStatsFromEnergyFeedsElecKwh(value) = new(value)
end # type SystemStatsFromEnergyFeedsElecKwh

function OpenAPI.property_type(::Type{ SystemStatsFromEnergyFeedsElecKwh }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsFromEnergyFeedsElecKwh, name)
end
