# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_combined_elec_kwh

    SystemStatsCombinedElecKwh(; value=nothing)
"""
mutable struct SystemStatsCombinedElecKwh <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsCombinedElecKwh() = new()
    SystemStatsCombinedElecKwh(value) = new(value)
end # type SystemStatsCombinedElecKwh

function OpenAPI.property_type(::Type{ SystemStatsCombinedElecKwh }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCombinedElecKwh, name)
end
