# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_starts_per_hour
Present in /system/stats/monthly entries.

    SystemStatsStartsPerHour(; value=nothing)
"""
mutable struct SystemStatsStartsPerHour <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsStartsPerHour() = new()
    SystemStatsStartsPerHour(value) = new(value)
end # type SystemStatsStartsPerHour

function OpenAPI.property_type(::Type{ SystemStatsStartsPerHour }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsStartsPerHour, name)
end
