# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemMeta_heatpump_heat_feedid
Feed ID for heat output. Returned as &#x60;false&#x60; for unauthenticated requests. /list only.

    SystemMetaHeatpumpHeatFeedid(; value=nothing)
"""
mutable struct SystemMetaHeatpumpHeatFeedid <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Bool, Int64 }
    SystemMetaHeatpumpHeatFeedid() = new()
    SystemMetaHeatpumpHeatFeedid(value) = new(value)
end # type SystemMetaHeatpumpHeatFeedid

function OpenAPI.property_type(::Type{ SystemMetaHeatpumpHeatFeedid }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemMetaHeatpumpHeatFeedid, name)
end
