# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemMeta_betateach

    SystemMetaBetateach(; value=nothing)
"""
mutable struct SystemMetaBetateach <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemMetaBetateach() = new()
    SystemMetaBetateach(value) = new(value)
end # type SystemMetaBetateach

function OpenAPI.property_type(::Type{ SystemMetaBetateach }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemMetaBetateach, name)
end
