# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_combined_prc_carnot
Fraction of Carnot efficiency.

    SystemStatsCombinedPrcCarnot(; value=nothing)
"""
mutable struct SystemStatsCombinedPrcCarnot <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsCombinedPrcCarnot() = new()
    SystemStatsCombinedPrcCarnot(value) = new(value)
end # type SystemStatsCombinedPrcCarnot

function OpenAPI.property_type(::Type{ SystemStatsCombinedPrcCarnot }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCombinedPrcCarnot, name)
end
