# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_combined_elec_mean
W.

    SystemStatsCombinedElecMean(; value=nothing)
"""
mutable struct SystemStatsCombinedElecMean <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsCombinedElecMean() = new()
    SystemStatsCombinedElecMean(value) = new(value)
end # type SystemStatsCombinedElecMean

function OpenAPI.property_type(::Type{ SystemStatsCombinedElecMean }, name::Symbol, json::Dict{String,Any})

    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCombinedElecMean, name)
end
