# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""BoundaryMetering
Which components fall inside the metering boundary for the system. Field types reflect the upstream API: most are tri-state booleans (&#x60;true&#x60;/&#x60;false&#x60;/&#x60;null&#x60;), &#x60;hydraulic_separation&#x60; is a free-text label.

    BoundaryMetering(;
        compressor=nothing,
        source_fan_or_brine=nothing,
        primary_pump_metered=nothing,
        secondary_pumps_metered=nothing,
        brine_pump_metered=nothing,
        immersion_heater_used=nothing,
        immersion_heater_metered=nothing,
        backup_heater_used=nothing,
        backup_heater_metered=nothing,
        hydraulic_separation=nothing,
    )

    - compressor::Bool
    - source_fan_or_brine::Bool
    - primary_pump_metered::Bool
    - secondary_pumps_metered::Bool
    - brine_pump_metered::Bool
    - immersion_heater_used::Bool
    - immersion_heater_metered::Bool
    - backup_heater_used::Bool
    - backup_heater_metered::Bool
    - hydraulic_separation::String
"""
Base.@kwdef mutable struct BoundaryMetering <: OpenAPI.APIModel
    compressor::Union{Nothing, Bool} = nothing
    source_fan_or_brine::Union{Nothing, Bool} = nothing
    primary_pump_metered::Union{Nothing, Bool} = nothing
    secondary_pumps_metered::Union{Nothing, Bool} = nothing
    brine_pump_metered::Union{Nothing, Bool} = nothing
    immersion_heater_used::Union{Nothing, Bool} = nothing
    immersion_heater_metered::Union{Nothing, Bool} = nothing
    backup_heater_used::Union{Nothing, Bool} = nothing
    backup_heater_metered::Union{Nothing, Bool} = nothing
    hydraulic_separation::Union{Nothing, String} = nothing

    function BoundaryMetering(compressor, source_fan_or_brine, primary_pump_metered, secondary_pumps_metered, brine_pump_metered, immersion_heater_used, immersion_heater_metered, backup_heater_used, backup_heater_metered, hydraulic_separation, )
        o = new(compressor, source_fan_or_brine, primary_pump_metered, secondary_pumps_metered, brine_pump_metered, immersion_heater_used, immersion_heater_metered, backup_heater_used, backup_heater_metered, hydraulic_separation, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type BoundaryMetering

const _property_types_BoundaryMetering = Dict{Symbol,String}(Symbol("compressor")=>"Bool", Symbol("source_fan_or_brine")=>"Bool", Symbol("primary_pump_metered")=>"Bool", Symbol("secondary_pumps_metered")=>"Bool", Symbol("brine_pump_metered")=>"Bool", Symbol("immersion_heater_used")=>"Bool", Symbol("immersion_heater_metered")=>"Bool", Symbol("backup_heater_used")=>"Bool", Symbol("backup_heater_metered")=>"Bool", Symbol("hydraulic_separation")=>"String", )
OpenAPI.property_type(::Type{ BoundaryMetering }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_BoundaryMetering[name]))}

function OpenAPI.check_required(o::BoundaryMetering)
    true
end

function OpenAPI.validate_properties(o::BoundaryMetering)
    OpenAPI.validate_property(BoundaryMetering, Symbol("compressor"), o.compressor)
    OpenAPI.validate_property(BoundaryMetering, Symbol("source_fan_or_brine"), o.source_fan_or_brine)
    OpenAPI.validate_property(BoundaryMetering, Symbol("primary_pump_metered"), o.primary_pump_metered)
    OpenAPI.validate_property(BoundaryMetering, Symbol("secondary_pumps_metered"), o.secondary_pumps_metered)
    OpenAPI.validate_property(BoundaryMetering, Symbol("brine_pump_metered"), o.brine_pump_metered)
    OpenAPI.validate_property(BoundaryMetering, Symbol("immersion_heater_used"), o.immersion_heater_used)
    OpenAPI.validate_property(BoundaryMetering, Symbol("immersion_heater_metered"), o.immersion_heater_metered)
    OpenAPI.validate_property(BoundaryMetering, Symbol("backup_heater_used"), o.backup_heater_used)
    OpenAPI.validate_property(BoundaryMetering, Symbol("backup_heater_metered"), o.backup_heater_metered)
    OpenAPI.validate_property(BoundaryMetering, Symbol("hydraulic_separation"), o.hydraulic_separation)
end

function OpenAPI.validate_property(::Type{ BoundaryMetering }, name::Symbol, val)










end
