# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_unit_rate_agile
Octopus Agile mean unit rate over the window (£/kWh).

    SystemStatsUnitRateAgile(; value=nothing)
"""
mutable struct SystemStatsUnitRateAgile <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsUnitRateAgile() = new()
    SystemStatsUnitRateAgile(value) = new(value)
end # type SystemStatsUnitRateAgile

function OpenAPI.property_type(::Type{ SystemStatsUnitRateAgile }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsUnitRateAgile, name)
end
