# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_combined_flowT_mean
°C.

    SystemStatsCombinedFlowTMean(; value=nothing)
"""
mutable struct SystemStatsCombinedFlowTMean <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Float64, String }
    SystemStatsCombinedFlowTMean() = new()
    SystemStatsCombinedFlowTMean(value) = new(value)
end # type SystemStatsCombinedFlowTMean

function OpenAPI.property_type(::Type{ SystemStatsCombinedFlowTMean }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCombinedFlowTMean, name)
end
