# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_id

    SystemStatsId(; value=nothing)
"""
mutable struct SystemStatsId <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemStatsId() = new()
    SystemStatsId(value) = new(value)
end # type SystemStatsId

function OpenAPI.property_type(::Type{ SystemStatsId }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsId, name)
end
