# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_combined_data_length
Seconds. Divide by 86400 for days.

    SystemStatsCombinedDataLength(; value=nothing)
"""
mutable struct SystemStatsCombinedDataLength <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemStatsCombinedDataLength() = new()
    SystemStatsCombinedDataLength(value) = new(value)
end # type SystemStatsCombinedDataLength

function OpenAPI.property_type(::Type{ SystemStatsCombinedDataLength }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCombinedDataLength, name)
end
