# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.



@doc raw"""SystemStats_combined_starts
Compressor start count.

    SystemStatsCombinedStarts(; value=nothing)
"""
mutable struct SystemStatsCombinedStarts <: OpenAPI.AnyOfAPIModel
    value::Any # Union{ Int64, String }
    SystemStatsCombinedStarts() = new()
    SystemStatsCombinedStarts(value) = new(value)
end # type SystemStatsCombinedStarts

function OpenAPI.property_type(::Type{ SystemStatsCombinedStarts }, name::Symbol, json::Dict{String,Any})
    
    # no discriminator specified, can't determine the exact type
    return fieldtype(SystemStatsCombinedStarts, name)
end
