# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""TimeseriesAvailable
Result of /timeseries/available?id&#x3D;...

    TimeseriesAvailable(;
        feeds=nothing,
        start_date=nothing,
        config_cache=nothing,
    )

    - feeds::Dict{String, TimeseriesFeed} : Map of feed name to feed descriptor.
    - start_date::Int64 : Earliest sample timestamp across all feeds (unix epoch seconds).
    - config_cache::Any
"""
Base.@kwdef mutable struct TimeseriesAvailable <: OpenAPI.APIModel
    feeds::Union{Nothing, Dict} = nothing # spec type: Union{ Nothing, Dict{String, TimeseriesFeed} }
    start_date::Union{Nothing, Int64} = nothing
    config_cache::Union{Nothing, Any} = nothing

    function TimeseriesAvailable(feeds, start_date, config_cache, )
        o = new(feeds, start_date, config_cache, )
        OpenAPI.validate_properties(o)
        return o
    end
end # type TimeseriesAvailable

const _property_types_TimeseriesAvailable = Dict{Symbol,String}(Symbol("feeds")=>"Dict{String, TimeseriesFeed}", Symbol("start_date")=>"Int64", Symbol("config_cache")=>"Any", )
OpenAPI.property_type(::Type{ TimeseriesAvailable }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_TimeseriesAvailable[name]))}

function OpenAPI.check_required(o::TimeseriesAvailable)
    o.feeds === nothing && (return false)
    true
end

function OpenAPI.validate_properties(o::TimeseriesAvailable)
    OpenAPI.validate_property(TimeseriesAvailable, Symbol("feeds"), o.feeds)
    OpenAPI.validate_property(TimeseriesAvailable, Symbol("start_date"), o.start_date)
    OpenAPI.validate_property(TimeseriesAvailable, Symbol("config_cache"), o.config_cache)
end

function OpenAPI.validate_property(::Type{ TimeseriesAvailable }, name::Symbol, val)



end
